GET http://localhost:3000/feed HTTP/1.1
content-type: application/json

{
   
}

###
POST http://localhost:3000/feed/forceUpdate HTTP/1.1
content-Type: application/json

{

}

###
POST http://localhost:3000/feed HTTP/1.1
content-Type: application/json

{
    "title": "Title1",
    "body": "Body1",
    "source": "Source1",
    "publisher": "Publisher1"
    
}
